home:
   path: /
   controller: App\Controller\IndexController

usersView:
   path: /user/{id}
   controller: App\Controller\UsersViewController

addFriend:
   path: /add-friend/{usersId}
   controller: App\Controller\AddFriendController

people:
   path: /people
   controller: App\Controller\PeopleController

login:
   path: /login
   controller: App\Controller\LoginController

logout:
   path: /logout
   controller: App\Controller\LogoutController

register:
   path: /register
   controller: App\Controller\RegisterController

search:
   path: /search
   controller: App\Controller\SearchController
   methods: [ GET ]

run:
   path: /run
   controller: App\Controller\RunController
   methods: [ GET ]